// Code generated by protoc-gen-go. DO NOT EDIT.
// source: web_log/web_log_pb/web_log.proto

package web_log_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SaveAllArticlesRequest struct {
	Article              string   `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveAllArticlesRequest) Reset()         { *m = SaveAllArticlesRequest{} }
func (m *SaveAllArticlesRequest) String() string { return proto.CompactTextString(m) }
func (*SaveAllArticlesRequest) ProtoMessage()    {}
func (*SaveAllArticlesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_306d5679ce324a28, []int{0}
}

func (m *SaveAllArticlesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveAllArticlesRequest.Unmarshal(m, b)
}
func (m *SaveAllArticlesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveAllArticlesRequest.Marshal(b, m, deterministic)
}
func (m *SaveAllArticlesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveAllArticlesRequest.Merge(m, src)
}
func (m *SaveAllArticlesRequest) XXX_Size() int {
	return xxx_messageInfo_SaveAllArticlesRequest.Size(m)
}
func (m *SaveAllArticlesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveAllArticlesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveAllArticlesRequest proto.InternalMessageInfo

func (m *SaveAllArticlesRequest) GetArticle() string {
	if m != nil {
		return m.Article
	}
	return ""
}

type SaveAllArticlesResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveAllArticlesResponse) Reset()         { *m = SaveAllArticlesResponse{} }
func (m *SaveAllArticlesResponse) String() string { return proto.CompactTextString(m) }
func (*SaveAllArticlesResponse) ProtoMessage()    {}
func (*SaveAllArticlesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_306d5679ce324a28, []int{1}
}

func (m *SaveAllArticlesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveAllArticlesResponse.Unmarshal(m, b)
}
func (m *SaveAllArticlesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveAllArticlesResponse.Marshal(b, m, deterministic)
}
func (m *SaveAllArticlesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveAllArticlesResponse.Merge(m, src)
}
func (m *SaveAllArticlesResponse) XXX_Size() int {
	return xxx_messageInfo_SaveAllArticlesResponse.Size(m)
}
func (m *SaveAllArticlesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveAllArticlesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveAllArticlesResponse proto.InternalMessageInfo

func (m *SaveAllArticlesResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GetAllArticlesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllArticlesRequest) Reset()         { *m = GetAllArticlesRequest{} }
func (m *GetAllArticlesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllArticlesRequest) ProtoMessage()    {}
func (*GetAllArticlesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_306d5679ce324a28, []int{2}
}

func (m *GetAllArticlesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllArticlesRequest.Unmarshal(m, b)
}
func (m *GetAllArticlesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllArticlesRequest.Marshal(b, m, deterministic)
}
func (m *GetAllArticlesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllArticlesRequest.Merge(m, src)
}
func (m *GetAllArticlesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllArticlesRequest.Size(m)
}
func (m *GetAllArticlesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllArticlesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllArticlesRequest proto.InternalMessageInfo

type GetAllArticlesResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllArticlesResponse) Reset()         { *m = GetAllArticlesResponse{} }
func (m *GetAllArticlesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllArticlesResponse) ProtoMessage()    {}
func (*GetAllArticlesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_306d5679ce324a28, []int{3}
}

func (m *GetAllArticlesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllArticlesResponse.Unmarshal(m, b)
}
func (m *GetAllArticlesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllArticlesResponse.Marshal(b, m, deterministic)
}
func (m *GetAllArticlesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllArticlesResponse.Merge(m, src)
}
func (m *GetAllArticlesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllArticlesResponse.Size(m)
}
func (m *GetAllArticlesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllArticlesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllArticlesResponse proto.InternalMessageInfo

func (m *GetAllArticlesResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GetSpecifiedArticleRequest struct {
	ArticleID            string   `protobuf:"bytes,1,opt,name=articleID,proto3" json:"articleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSpecifiedArticleRequest) Reset()         { *m = GetSpecifiedArticleRequest{} }
func (m *GetSpecifiedArticleRequest) String() string { return proto.CompactTextString(m) }
func (*GetSpecifiedArticleRequest) ProtoMessage()    {}
func (*GetSpecifiedArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_306d5679ce324a28, []int{4}
}

func (m *GetSpecifiedArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpecifiedArticleRequest.Unmarshal(m, b)
}
func (m *GetSpecifiedArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpecifiedArticleRequest.Marshal(b, m, deterministic)
}
func (m *GetSpecifiedArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpecifiedArticleRequest.Merge(m, src)
}
func (m *GetSpecifiedArticleRequest) XXX_Size() int {
	return xxx_messageInfo_GetSpecifiedArticleRequest.Size(m)
}
func (m *GetSpecifiedArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpecifiedArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpecifiedArticleRequest proto.InternalMessageInfo

func (m *GetSpecifiedArticleRequest) GetArticleID() string {
	if m != nil {
		return m.ArticleID
	}
	return ""
}

type GetSpecifiedArticleResponse struct {
	ArticleID            string   `protobuf:"bytes,1,opt,name=articleID,proto3" json:"articleID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSpecifiedArticleResponse) Reset()         { *m = GetSpecifiedArticleResponse{} }
func (m *GetSpecifiedArticleResponse) String() string { return proto.CompactTextString(m) }
func (*GetSpecifiedArticleResponse) ProtoMessage()    {}
func (*GetSpecifiedArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_306d5679ce324a28, []int{5}
}

func (m *GetSpecifiedArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpecifiedArticleResponse.Unmarshal(m, b)
}
func (m *GetSpecifiedArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpecifiedArticleResponse.Marshal(b, m, deterministic)
}
func (m *GetSpecifiedArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpecifiedArticleResponse.Merge(m, src)
}
func (m *GetSpecifiedArticleResponse) XXX_Size() int {
	return xxx_messageInfo_GetSpecifiedArticleResponse.Size(m)
}
func (m *GetSpecifiedArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpecifiedArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpecifiedArticleResponse proto.InternalMessageInfo

func (m *GetSpecifiedArticleResponse) GetArticleID() string {
	if m != nil {
		return m.ArticleID
	}
	return ""
}

func (m *GetSpecifiedArticleResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetSpecifiedArticleResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type UpdateSpecifiedArticleRequest struct {
	ArticleID            string   `protobuf:"bytes,1,opt,name=articleID,proto3" json:"articleID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSpecifiedArticleRequest) Reset()         { *m = UpdateSpecifiedArticleRequest{} }
func (m *UpdateSpecifiedArticleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSpecifiedArticleRequest) ProtoMessage()    {}
func (*UpdateSpecifiedArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_306d5679ce324a28, []int{6}
}

func (m *UpdateSpecifiedArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSpecifiedArticleRequest.Unmarshal(m, b)
}
func (m *UpdateSpecifiedArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSpecifiedArticleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSpecifiedArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSpecifiedArticleRequest.Merge(m, src)
}
func (m *UpdateSpecifiedArticleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSpecifiedArticleRequest.Size(m)
}
func (m *UpdateSpecifiedArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSpecifiedArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSpecifiedArticleRequest proto.InternalMessageInfo

func (m *UpdateSpecifiedArticleRequest) GetArticleID() string {
	if m != nil {
		return m.ArticleID
	}
	return ""
}

func (m *UpdateSpecifiedArticleRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateSpecifiedArticleRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type UpdateSpecifiedArticleResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSpecifiedArticleResponse) Reset()         { *m = UpdateSpecifiedArticleResponse{} }
func (m *UpdateSpecifiedArticleResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSpecifiedArticleResponse) ProtoMessage()    {}
func (*UpdateSpecifiedArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_306d5679ce324a28, []int{7}
}

func (m *UpdateSpecifiedArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSpecifiedArticleResponse.Unmarshal(m, b)
}
func (m *UpdateSpecifiedArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSpecifiedArticleResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSpecifiedArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSpecifiedArticleResponse.Merge(m, src)
}
func (m *UpdateSpecifiedArticleResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSpecifiedArticleResponse.Size(m)
}
func (m *UpdateSpecifiedArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSpecifiedArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSpecifiedArticleResponse proto.InternalMessageInfo

func (m *UpdateSpecifiedArticleResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type RemoveSpecifiedArticleRequest struct {
	ArticleID            string   `protobuf:"bytes,1,opt,name=articleID,proto3" json:"articleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSpecifiedArticleRequest) Reset()         { *m = RemoveSpecifiedArticleRequest{} }
func (m *RemoveSpecifiedArticleRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveSpecifiedArticleRequest) ProtoMessage()    {}
func (*RemoveSpecifiedArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_306d5679ce324a28, []int{8}
}

func (m *RemoveSpecifiedArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSpecifiedArticleRequest.Unmarshal(m, b)
}
func (m *RemoveSpecifiedArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSpecifiedArticleRequest.Marshal(b, m, deterministic)
}
func (m *RemoveSpecifiedArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSpecifiedArticleRequest.Merge(m, src)
}
func (m *RemoveSpecifiedArticleRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveSpecifiedArticleRequest.Size(m)
}
func (m *RemoveSpecifiedArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSpecifiedArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSpecifiedArticleRequest proto.InternalMessageInfo

func (m *RemoveSpecifiedArticleRequest) GetArticleID() string {
	if m != nil {
		return m.ArticleID
	}
	return ""
}

type RemoveSpecifiedArticleResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveSpecifiedArticleResponse) Reset()         { *m = RemoveSpecifiedArticleResponse{} }
func (m *RemoveSpecifiedArticleResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveSpecifiedArticleResponse) ProtoMessage()    {}
func (*RemoveSpecifiedArticleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_306d5679ce324a28, []int{9}
}

func (m *RemoveSpecifiedArticleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveSpecifiedArticleResponse.Unmarshal(m, b)
}
func (m *RemoveSpecifiedArticleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveSpecifiedArticleResponse.Marshal(b, m, deterministic)
}
func (m *RemoveSpecifiedArticleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveSpecifiedArticleResponse.Merge(m, src)
}
func (m *RemoveSpecifiedArticleResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveSpecifiedArticleResponse.Size(m)
}
func (m *RemoveSpecifiedArticleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveSpecifiedArticleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveSpecifiedArticleResponse proto.InternalMessageInfo

func (m *RemoveSpecifiedArticleResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*SaveAllArticlesRequest)(nil), "web_log.SaveAllArticlesRequest")
	proto.RegisterType((*SaveAllArticlesResponse)(nil), "web_log.SaveAllArticlesResponse")
	proto.RegisterType((*GetAllArticlesRequest)(nil), "web_log.GetAllArticlesRequest")
	proto.RegisterType((*GetAllArticlesResponse)(nil), "web_log.GetAllArticlesResponse")
	proto.RegisterType((*GetSpecifiedArticleRequest)(nil), "web_log.GetSpecifiedArticleRequest")
	proto.RegisterType((*GetSpecifiedArticleResponse)(nil), "web_log.GetSpecifiedArticleResponse")
	proto.RegisterType((*UpdateSpecifiedArticleRequest)(nil), "web_log.UpdateSpecifiedArticleRequest")
	proto.RegisterType((*UpdateSpecifiedArticleResponse)(nil), "web_log.UpdateSpecifiedArticleResponse")
	proto.RegisterType((*RemoveSpecifiedArticleRequest)(nil), "web_log.RemoveSpecifiedArticleRequest")
	proto.RegisterType((*RemoveSpecifiedArticleResponse)(nil), "web_log.RemoveSpecifiedArticleResponse")
}

func init() { proto.RegisterFile("web_log/web_log_pb/web_log.proto", fileDescriptor_306d5679ce324a28) }

var fileDescriptor_306d5679ce324a28 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcd, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xe1, 0x25, 0x2f, 0x84, 0x89, 0x1f, 0xc9, 0xaa, 0xa5, 0xa9, 0xf2, 0x91, 0xd5, 0x28,
	0x27, 0x54, 0xbc, 0x18, 0x13, 0x0f, 0x18, 0x13, 0x62, 0xe2, 0x89, 0xc6, 0x68, 0xbc, 0x10, 0x5a,
	0x46, 0xd2, 0xb0, 0xb0, 0xb5, 0x5d, 0xf0, 0x9f, 0xf7, 0x60, 0xa0, 0x5b, 0xa8, 0xb0, 0x5d, 0x22,
	0xa7, 0x76, 0x76, 0xe6, 0x99, 0xdf, 0x64, 0xf6, 0xc9, 0x42, 0xed, 0x0b, 0x9d, 0x2e, 0xe3, 0x83,
	0x4b, 0xf9, 0xed, 0xfa, 0x4e, 0xfc, 0xdb, 0xf0, 0x03, 0x2e, 0x38, 0x29, 0xc8, 0x90, 0x36, 0xc1,
	0xb0, 0x7b, 0x53, 0x6c, 0x31, 0xd6, 0x0a, 0x84, 0xe7, 0x32, 0x0c, 0x3b, 0xf8, 0x39, 0xc1, 0x50,
	0x10, 0x13, 0x0a, 0xbd, 0xe8, 0xc8, 0xcc, 0xd6, 0xb2, 0xf5, 0x62, 0x27, 0x0e, 0xe9, 0x35, 0x94,
	0xd6, 0x34, 0xa1, 0xcf, 0xc7, 0x21, 0x12, 0x03, 0xf2, 0x01, 0x86, 0x13, 0x26, 0xa4, 0x46, 0x46,
	0xb4, 0x04, 0x47, 0x6d, 0x14, 0xeb, 0x14, 0x7a, 0x05, 0xc6, 0x6a, 0x62, 0x43, 0xab, 0x3b, 0xb0,
	0xda, 0x28, 0x6c, 0x1f, 0x5d, 0xef, 0xc3, 0xc3, 0xbe, 0xd4, 0xc5, 0x53, 0x9f, 0x40, 0x51, 0x8e,
	0xf9, 0xf4, 0x28, 0x85, 0xcb, 0x03, 0x3a, 0x84, 0x63, 0xa5, 0x56, 0x22, 0xb5, 0x62, 0x72, 0x08,
	0xff, 0x85, 0x27, 0x18, 0x9a, 0xff, 0xe6, 0x99, 0x28, 0x98, 0xad, 0xc9, 0xe5, 0x63, 0x81, 0x63,
	0x61, 0xe6, 0xa2, 0x35, 0xc9, 0x90, 0x8e, 0xa0, 0xfc, 0xe2, 0xf7, 0x7b, 0x02, 0xb7, 0x9a, 0xf5,
	0xcf, 0xb8, 0x5b, 0xa8, 0xa4, 0xe1, 0x36, 0x6c, 0xf4, 0x1e, 0xca, 0x1d, 0x1c, 0xf1, 0xe9, 0x76,
	0x83, 0xce, 0xc0, 0x69, 0x72, 0x3d, 0xb8, 0xf9, 0x9d, 0x83, 0xdd, 0x57, 0x74, 0x9e, 0xf9, 0xc0,
	0xc6, 0x60, 0xea, 0xb9, 0x48, 0xde, 0x60, 0x7f, 0xc5, 0x5a, 0xa4, 0xda, 0x88, 0xad, 0xab, 0x36,
	0xaa, 0x55, 0x4b, 0x2f, 0x88, 0xf8, 0x34, 0x53, 0xcf, 0x12, 0x1b, 0xf6, 0x7e, 0x1b, 0x8d, 0x54,
	0x16, 0x3a, 0xa5, 0x35, 0xad, 0x6a, 0x6a, 0x3e, 0x6e, 0x4b, 0x1c, 0x38, 0x50, 0xf8, 0x89, 0x9c,
	0x26, 0x95, 0x29, 0x4b, 0xb5, 0xce, 0xf4, 0x45, 0x0b, 0xc6, 0x10, 0x0c, 0xf5, 0xbd, 0x92, 0xf3,
	0x45, 0x07, 0xad, 0xcf, 0xac, 0x8b, 0x8d, 0x75, 0x49, 0x98, 0xfa, 0x2e, 0x13, 0x30, 0xad, 0x57,
	0x12, 0x30, 0xbd, 0x29, 0x68, 0xe6, 0x61, 0xe7, 0x1d, 0x96, 0x0f, 0x94, 0x93, 0x9f, 0xbf, 0x4c,
	0x37, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf4, 0xf5, 0xca, 0xfc, 0xbd, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WebLogServiceClient is the client API for WebLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WebLogServiceClient interface {
	// Client Streaming
	SaveAllArticles(ctx context.Context, opts ...grpc.CallOption) (WebLogService_SaveAllArticlesClient, error)
	// Unary
	GetAllArticles(ctx context.Context, in *GetAllArticlesRequest, opts ...grpc.CallOption) (*GetAllArticlesResponse, error)
	// Unary
	GetSpecifiedArticle(ctx context.Context, in *GetSpecifiedArticleRequest, opts ...grpc.CallOption) (*GetSpecifiedArticleResponse, error)
	// Unary
	UpdateSpecifiedArticle(ctx context.Context, in *UpdateSpecifiedArticleRequest, opts ...grpc.CallOption) (*UpdateSpecifiedArticleResponse, error)
	// Unary
	RemoveSpecifiedArticle(ctx context.Context, in *RemoveSpecifiedArticleRequest, opts ...grpc.CallOption) (*RemoveSpecifiedArticleResponse, error)
}

type webLogServiceClient struct {
	cc *grpc.ClientConn
}

func NewWebLogServiceClient(cc *grpc.ClientConn) WebLogServiceClient {
	return &webLogServiceClient{cc}
}

func (c *webLogServiceClient) SaveAllArticles(ctx context.Context, opts ...grpc.CallOption) (WebLogService_SaveAllArticlesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WebLogService_serviceDesc.Streams[0], "/web_log.WebLogService/SaveAllArticles", opts...)
	if err != nil {
		return nil, err
	}
	x := &webLogServiceSaveAllArticlesClient{stream}
	return x, nil
}

type WebLogService_SaveAllArticlesClient interface {
	Send(*SaveAllArticlesRequest) error
	CloseAndRecv() (*SaveAllArticlesResponse, error)
	grpc.ClientStream
}

type webLogServiceSaveAllArticlesClient struct {
	grpc.ClientStream
}

func (x *webLogServiceSaveAllArticlesClient) Send(m *SaveAllArticlesRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *webLogServiceSaveAllArticlesClient) CloseAndRecv() (*SaveAllArticlesResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SaveAllArticlesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *webLogServiceClient) GetAllArticles(ctx context.Context, in *GetAllArticlesRequest, opts ...grpc.CallOption) (*GetAllArticlesResponse, error) {
	out := new(GetAllArticlesResponse)
	err := c.cc.Invoke(ctx, "/web_log.WebLogService/GetAllArticles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webLogServiceClient) GetSpecifiedArticle(ctx context.Context, in *GetSpecifiedArticleRequest, opts ...grpc.CallOption) (*GetSpecifiedArticleResponse, error) {
	out := new(GetSpecifiedArticleResponse)
	err := c.cc.Invoke(ctx, "/web_log.WebLogService/GetSpecifiedArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webLogServiceClient) UpdateSpecifiedArticle(ctx context.Context, in *UpdateSpecifiedArticleRequest, opts ...grpc.CallOption) (*UpdateSpecifiedArticleResponse, error) {
	out := new(UpdateSpecifiedArticleResponse)
	err := c.cc.Invoke(ctx, "/web_log.WebLogService/UpdateSpecifiedArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webLogServiceClient) RemoveSpecifiedArticle(ctx context.Context, in *RemoveSpecifiedArticleRequest, opts ...grpc.CallOption) (*RemoveSpecifiedArticleResponse, error) {
	out := new(RemoveSpecifiedArticleResponse)
	err := c.cc.Invoke(ctx, "/web_log.WebLogService/RemoveSpecifiedArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebLogServiceServer is the server API for WebLogService service.
type WebLogServiceServer interface {
	// Client Streaming
	SaveAllArticles(WebLogService_SaveAllArticlesServer) error
	// Unary
	GetAllArticles(context.Context, *GetAllArticlesRequest) (*GetAllArticlesResponse, error)
	// Unary
	GetSpecifiedArticle(context.Context, *GetSpecifiedArticleRequest) (*GetSpecifiedArticleResponse, error)
	// Unary
	UpdateSpecifiedArticle(context.Context, *UpdateSpecifiedArticleRequest) (*UpdateSpecifiedArticleResponse, error)
	// Unary
	RemoveSpecifiedArticle(context.Context, *RemoveSpecifiedArticleRequest) (*RemoveSpecifiedArticleResponse, error)
}

// UnimplementedWebLogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWebLogServiceServer struct {
}

func (*UnimplementedWebLogServiceServer) SaveAllArticles(srv WebLogService_SaveAllArticlesServer) error {
	return status.Errorf(codes.Unimplemented, "method SaveAllArticles not implemented")
}
func (*UnimplementedWebLogServiceServer) GetAllArticles(ctx context.Context, req *GetAllArticlesRequest) (*GetAllArticlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllArticles not implemented")
}
func (*UnimplementedWebLogServiceServer) GetSpecifiedArticle(ctx context.Context, req *GetSpecifiedArticleRequest) (*GetSpecifiedArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpecifiedArticle not implemented")
}
func (*UnimplementedWebLogServiceServer) UpdateSpecifiedArticle(ctx context.Context, req *UpdateSpecifiedArticleRequest) (*UpdateSpecifiedArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSpecifiedArticle not implemented")
}
func (*UnimplementedWebLogServiceServer) RemoveSpecifiedArticle(ctx context.Context, req *RemoveSpecifiedArticleRequest) (*RemoveSpecifiedArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSpecifiedArticle not implemented")
}

func RegisterWebLogServiceServer(s *grpc.Server, srv WebLogServiceServer) {
	s.RegisterService(&_WebLogService_serviceDesc, srv)
}

func _WebLogService_SaveAllArticles_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WebLogServiceServer).SaveAllArticles(&webLogServiceSaveAllArticlesServer{stream})
}

type WebLogService_SaveAllArticlesServer interface {
	SendAndClose(*SaveAllArticlesResponse) error
	Recv() (*SaveAllArticlesRequest, error)
	grpc.ServerStream
}

type webLogServiceSaveAllArticlesServer struct {
	grpc.ServerStream
}

func (x *webLogServiceSaveAllArticlesServer) SendAndClose(m *SaveAllArticlesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *webLogServiceSaveAllArticlesServer) Recv() (*SaveAllArticlesRequest, error) {
	m := new(SaveAllArticlesRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _WebLogService_GetAllArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebLogServiceServer).GetAllArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/web_log.WebLogService/GetAllArticles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebLogServiceServer).GetAllArticles(ctx, req.(*GetAllArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebLogService_GetSpecifiedArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpecifiedArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebLogServiceServer).GetSpecifiedArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/web_log.WebLogService/GetSpecifiedArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebLogServiceServer).GetSpecifiedArticle(ctx, req.(*GetSpecifiedArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebLogService_UpdateSpecifiedArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSpecifiedArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebLogServiceServer).UpdateSpecifiedArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/web_log.WebLogService/UpdateSpecifiedArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebLogServiceServer).UpdateSpecifiedArticle(ctx, req.(*UpdateSpecifiedArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebLogService_RemoveSpecifiedArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSpecifiedArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebLogServiceServer).RemoveSpecifiedArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/web_log.WebLogService/RemoveSpecifiedArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebLogServiceServer).RemoveSpecifiedArticle(ctx, req.(*RemoveSpecifiedArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WebLogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "web_log.WebLogService",
	HandlerType: (*WebLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllArticles",
			Handler:    _WebLogService_GetAllArticles_Handler,
		},
		{
			MethodName: "GetSpecifiedArticle",
			Handler:    _WebLogService_GetSpecifiedArticle_Handler,
		},
		{
			MethodName: "UpdateSpecifiedArticle",
			Handler:    _WebLogService_UpdateSpecifiedArticle_Handler,
		},
		{
			MethodName: "RemoveSpecifiedArticle",
			Handler:    _WebLogService_RemoveSpecifiedArticle_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SaveAllArticles",
			Handler:       _WebLogService_SaveAllArticles_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "web_log/web_log_pb/web_log.proto",
}
